admin/urls.py
from django.conf.urls import patterns, url, include
from admin import views

urlpatterns = patterns('',
                       url("^nurses/{0,1}?",
                           views.ListNurses.as_view(),
                           name = "list_nurses"))
                           

nurses/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from tastypie.api import Api
from admin.api.resources import NurseResource

v1_api = Api(api_name='v1')
v1_api.register(NurseResource())

urlpatterns = patterns('',
                       url(r'^params/', include('parameters.urls', namespace="params")),
                       url(r'^admin/', include('admin.urls', namespace="admin")),
                       url(r'^api/', include(v1_api.urls))
    # Examples:
    # url(r'^$', 'nurses.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
                       
)

parameters/urls.py
from django.conf.urls import patterns, url
from parameters import views

urlpatterns = patterns('',
                       url(r"list/{0,1}$", views.ListParams.as_view(), name="list"),
                       url(r"view/(?P<id_par>[a-z0-9]+)/{0,1}$", views.param, name="view"),
                       url(r"create/{0,1}$", views.CreateParam.as_view(), name="create"),
                       url(r"edit/(?P<id_par>[a-z0-9]+)/{0,1}$", 
                           views.EditParam.as_view(),
                           name = "edit"
                       ))
                       
                       
    

admin/models.py
from nurses.db import Base, Session
from sqlalchemy import Column, Integer, String, Boolean

class Nurse(Base):
    __tablename__ = "nurse"

    id = Column(Integer, primary_key = True,
                autoincrement = True)
    last_name = Column(String(200))
    first_name = Column(String(150))
    
    experienced = Column(Boolean(), default = False)

base/models.py
from django.db import models

# Create your models here.

parameters/models.py
from nurses.db import Base, Session
from sqlalchemy import Column, Float, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship, backref 
from datetime import datetime
# Create your models here.


class Scenario(Base):
    __tablename__ = "scenario"
    
    id_scenario = Column(String(256), primary_key=True)
    timestamp = Column(DateTime, default=datetime.now())

class Parameter(Base):
    __tablename__ = "parameter"

    id_par = Column(String(20), primary_key=True)
    id_scenario = Column(String(256), ForeignKey("scenario.id_scenario"), primary_key=True, nullable=True)
    scenario = relationship("Scenario", backref=backref("parameters"))
    
    number = Column(Float)
    text = Column(Text)
    

admin/forms.py
from django import forms
from django.utils.translation import ugettext as _
from djangular.forms.angular_model import NgModelFormMixin

class NurseForm(NgModelFormMixin, forms.Form):
    first_name = forms.CharField(
        label = _("First Name"),
        required = True)
    last_name = forms.CharField(
        label = _("Last Name"),
        required = True)
    experienced = forms.BooleanField(
        label = _("Experienced"))

    def __init__(self, *args, **kwargs):
        kwargs.update(scope_prefix='nurse')
        super(NurseForm, self).__init__(*args, **kwargs)

parameters/forms.py
from django import forms


class ParamForm(forms.Form):
    id = forms.CharField(
        max_length=20)
    value = forms.FloatField()
    text = forms.CharField(
        widget = forms.Textarea)
    

admin/views.py
from django.shortcuts import render
from django.views.generic.base import View
# Create your views here.
from nurses.db import Session
from admin.models import Nurse
from admin.forms import NurseForm

class ListNurses(View):
    
    def get(self, request, *args, **kwargs):
        nurses = Session().query(Nurse).all()
        form = NurseForm()
        return render(request, "admin/nurses_list.html",
                      {"nurses": nurses,
                       "form": form,
                       "angular_app": "NursesApp"
                   })
        

base/views.py
from django.shortcuts import render

# Create your views here.

parameters/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.
from parameters.models import Parameter
from nurses.db import Session
from .forms import ParamForm
from django.shortcuts import render

from django.views.generic.base import View


def param(request, id_par):
    print(id_par)
    return HttpResponse("hello {par}".format(par=id_par))

class ListParams(View):
    def get(self, request, *args, **kwargs):
        session = Session()
        params = session.query(Parameter).all()
        return render(request, "parameters/list.html", {"params": params})

class CreateParam(View):
    form_cls = ParamForm
    title = "Create Parameter"
    def get(self, request, *args, **kwargs):
        form = self.form_cls()
        context = dict(
            form = form,
            title = self.title)
        return render(request, "parameters/create.html", context)
    
    def post(self, request, *args, **kwargs):
        
        form = self.form_cls(request.POST)

        if form.is_valid():
            param = Parameter(id_par = form.cleaned_data['id'],
                              number = form.cleaned_data['value'],
                              text = form.cleaned_data['text'],
                              id_scenario = "dummy")

            session = Session()
            session.add(param)
            session.commit()

            return HttpResponseRedirect("/params/list")

        context = dict(
            form = form,
            title = self.title)
        return render(request, "parameters/create.html", context)
            

class EditParam(View):
    form_cls = ParamForm
    title = "Edit parameter"
    def get(self, request, id_par, *args, **kwargs):
        session = Session()
        param = session.query(Parameter).filter_by(id_par=id_par).first()
        form = self.form_cls(dict(
            id = param.id_par,
            value = param.number,
            text = param.text))
        context = dict(
            title = self.title,
            form = form,
            param = param)
        
        return render(request, "parameters/create.html", context)

    def post(self, request, id_par, *args, **kwargs):
        """
        
        Arguments:
        - `request`:
        - `id_par`:
        - `*args`:
        - `**kwargs`:
        """
        
        session = Session()
        param = session.query(Parameter).filter_by(id_par=id_par).first()
        form = self.form_cls(request.POST)
        if form.is_valid():
            
            data = form.cleaned_data
            param.id_par = data['id']
            param.number = data['value']
            param.text = data['text']

            session.commit()
            
        context = dict(
            form = form,
            title = self.title,
            param = param)

        return render(request, "parameters/create.html", context)
        
        

        

base/templates/base.html
<!DOCTYPE html>
{% load static from staticfiles %}
{% load bootstrap3 %}
{% load url from future %}

{% bootstrap_messages %}

<html lang="en" ng-app="{% if angular_app %}{{ angular_app }}{% endif %}">
<head>
    <meta charset="utf-8">
    <title>Sestre</title>
    <meta name="description" content="">
    <meta name="author" content="Sasha Shipka">
    
    {% bootstrap_css %}
    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="{% static 'js/angular.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/angular-resource.min.js' %}"></script>
    {% bootstrap_javascript %}

    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block extra_head %}{% endblock %}
</head>

<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Sestre</a>
    </div>
      <ul class="nav navbar-nav">
	<li><a href="{% url 'params:list' %}">Parameters</a></li>
	<li> <a href="{% url 'admin:list_nurses' %}">Nurses</a></li>
      </ul>
</nav>

<div class="container">

    {% bootstrap_messages %}

    {% block content %}Empty page{% endblock %}

    <p><hr></p>

    <footer class="row">
        <div class="span6">
        </div>
    </footer>

</div> <!-- container -->

{% block modal_forms %}
{% endblock %}

</body>
</html>

parameters/templates/parameters/create.html
{% extends "base.html" %}

{% load bootstrap_toolkit %}

{% block content %}
<h4>{{ title }}</h4>
<form class="form-horizontal" method="post" id="" action="">
  {% csrf_token %}
  {{ form|as_bootstrap }}
  <div class="form-actions">
    {% if param %}
    <input type="submit" class="btn btn-primary" name="" value="Save" />
    {% else %}
    <input type="submit" class="btn btn-primary" name="" value="Create" />
    {% endif %}
  </div>
</form>
{% endblock %}

parameters/templates/parameters/list.html
{% extends "base.html" %}

{% load bootstrap_toolkit %}

{% block content %}
<h4>Existing parameters</h4>
<table class="table table-striped">
  <tr>
    <th>Id</th>
    <th>Number</th>
    <th>Text</th>
  </tr>
  {% for param in params %}
  <tr>
    <td>{{ param.id_par }}</td>
    <td>{{ param.number }}</td>
    <td>{{ param.text }}</td>
  </tr>
  {% endfor %}
</table>

{% endblock %}
  